### ISSUE TITLE
Fileno Error

### ISSUE THREAD

**Issue by yaxirhuxxain** [naturalness/javac-parser#3]
When i run the following command "java = javac_parser.Java()" i get this error.

Traceback (most recent call last):

  File "<ipython-input-283-277a7e9aa26d>", line 2, in <module>
    java = javac_parser.Java()

  File "C:\ProgramData\Anaconda3\lib\site-packages\javac_parser\javac_parser.py", line 88, in __init__
    redirect_stderr=sys.stderr)

  File "C:\ProgramData\Anaconda3\lib\site-packages\py4j\java_gateway.py", line 313, in launch_gateway
    **popen_kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 210, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 667, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 942, in _get_handles
    errwrite = msvcrt.get_osfhandle(stderr.fileno())

UnsupportedOperation: fileno

**Comment by eddieantonio** [comment]
Unfortunately, this is an issue in the library we use, [py4j](https://www.py4j.org/), which does not support Windows. `fileno()` is an operation that is only supported on Unix (Linux, macOS, etc.) devices. If possible, run javac-parser in Linux Subsystem for Windows, or a Linux virtualmachine. Sorry about that! :/
